### ISSUE TITLE
Plans to support Craft CMS 5?

### ISSUE THREAD

**Issue by chloe-pfr** [DeuxHuitHuit/craft-cloudflare-images#2]
Hi there,
Is there any chance you're planning to support Craft 5? I'm an existing customer and it would be helpful to have the built-in asset manager instead of a bunch of fields.

Thanks

**Comment by nitriques** [comment]
Hi @chloe-pfr 

Sorry for the late response, but Craft 5 is now available !
https://github.com/DeuxHuitHuit/craft-cloudflare-images/releases/tag/2.0.0

Thanks!
